### ISSUE TITLE
[Non-issue] Revoke location permission for GMS?

### ISSUE THREAD

**Issue by ghost** [gloeyisk/universal-gms-doze#8]
GMS accesses location in background periodically, and there is no way to revoke that in permission settings or `pm` command.

![Screenshot_2022-03-29_01-53-12](https://user-images.githubusercontent.com/40300931/160530110-7960cdd7-8a08-45d4-bd91-936f0b7a29b5.png)

```
# pm revoke com.google.android.gms android.permission.ACCESS_BACKGROUND_LOCATION  

Exception occurred while executing 'revoke':
java.lang.SecurityException: Non-System UID cannot revoke system fixed permission android.permission.ACCESS_BACKGROUND_LOCATION for package com.google.android.gms
        at com.android.server.pm.permission.PermissionManagerService.revokeRuntimePermissionInternal(PermissionManagerService.java:1706)
        at com.android.server.pm.permission.PermissionManagerService.revokeRuntimePermission(PermissionManagerService.java:1613)
        at android.permission.PermissionManager.revokeRuntimePermission(PermissionManager.java:419)
        at com.android.server.pm.PackageManagerShellCommand.runGrantRevokePermission(PackageManagerShellCommand.java:2386)
        at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:262)
        at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
        at android.os.ShellCommand.exec(ShellCommand.java:38)
        at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:24817)
        at android.os.Binder.shellCommand(Binder.java:950)
        at android.os.Binder.onTransact(Binder.java:834)
        at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:4818)
        at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:8890)
        at android.os.Binder.execTransactInternal(Binder.java:1184)
        at android.os.Binder.execTransact(Binder.java:1143)
```

Disabling Google location services won't help, GMS still collects location in background.

Therefore I'm looking into patching system configurations to allow location permission to be revoked. 

---

The first thing came into mind was this universal GMS doze module, as it tries to do similar things: revoking permission from GMS.

```
gms=$(xml=$(find /system/ /product/ /vendor/ -iname "*.xml");for i in $xml; do if grep -q 'allow-in-power-save package="com.google.android.gms"' $ROOT$i 2>/dev/null; then echo "$i";fi; done)

...

sed -i '/allow-in-power-save package="com.google.android.gms"/d;/allow-in-data-usage-save package="com.google.android.gms"/d' $MODPATH$i
```

It appears to do strings searching and deleting, and that's enough to allow doze for GMS.

---

Things (that looks like being) related to location permission:
`/product/etc/sysconfig/google.xml`

```
    <!-- GmsCore must always have network access for GCM and other things. -->
    <allow-unthrottled-location package="com.google.android.gms" />
    <allow-ignore-location-settings package="com.google.android.gms" attributionTag="com.google.android.gms.thunderbird" />
```

So I copied and modified scripts in universal GMS doze to be like this:

```
#!/sbin/sh

#
# Universal GMS Doze by the
# open source loving GL-DP and all contributors;
# Patches Google Play services app and its background processes to be able using battery optimization
#

# Checking for installation environment
if [ $BOOTMODE = true ]; then
ROOT=$(find `magisk --path` -type d -name "mirror" | head -n 1)
ui_print "- Root path: $ROOT"
else
ROOT=""
fi

# Check device SDK
sdk="$(getprop ro.build.version.sdk)"
if [[ !"$sdk" -ge "23" ]]; then
ui_print "- Unsupported SDK version: $sdk"
exit 1
fi

# Patch the XML and place the modified one to the original directory
ui_print "- Patching XML files"
location=$(xml=$(find /system/ /product/ /vendor/ -iname "*.xml");for i in $xml; do if grep -q 'allow-unthrottled-location package="com.google.android.gms"' $ROOT$i 2>/dev/null; then echo "$i";fi; done)
ignore=$(xml=$(find /system/ /product/ /vendor/ -iname "*.xml");for i in $xml; do if grep -q 'allow-ignore-location-settings package="com.google.android.gms"' $ROOT$i 2>/dev/null; then echo "$i";fi; done)

for i in $location $ignore
do
mkdir -p `dirname $MODPATH$i`
cp -af $ROOT$i $MODPATH$i
sed -i '/allow-unthrottled-location package="com.google.android.gms"/d;/allow-ignore-location-settings package="com.google.android.gms"/d' $MODPATH$i
done

for i in product vendor
do
if [ -d $MODPATH/$i ]; then
if [ ! -d $MODPATH/system/$i ]; then
sleep 1
ui_print "- Moving files to /system partition"
mkdir -p $MODPATH/system/$i
mv -f $MODPATH/$i $MODPATH/system/
else
rm -rf $MODPATH/$i
fi
fi
done

# Search and patch any conflicting modules (if present)
# Search conflicting XML files
conflict1=$(xml=$(find /data/adb -iname "*.xml");for i in $xml; do if grep -q 'allow-unthrottled-location package="com.google.android.gms"' $i 2>/dev/null; then echo "$i";fi; done)
conflict2=$(xml=$(find /data/adb -iname "*.xml");for i in $xml; do if grep -q 'allow-ignore-location-settings package="com.google.android.gms"' $i 2>/dev/null; then echo "$i";fi; done)
for i in $conflict1 $conflict2
do
search=$(echo "$i" | sed -e 's/\// /g' | awk '{print $4}')
ui_print "- Conflicting modules detected"
ui_print "   $search"
sed -i '/allow-unthrottled-location package="com.google.android.gms"/d;/allow-ignore-location-settings package="com.google.android.gms"/d' $i
done

# Clean up
rm -rf $MODPATH/LICENSE

```

However, that's where the modding stops, as I don't know how to build a proper magisk module.
Can you use this to duplicate a new module for location permission?

---

I know the fact GMS being a location service and address lookup provider, but I don't want to use that.

**Comment by gloeyisk** [comment]
It's added now. Closing.
